export const stateData = { // eslint-disable-line
  AL: { fullName: 'Alabama', region: 'SE' },
  AK: { fullName: 'Alaska', region: 'NW' },
  AZ: { fullName: 'Arizona', region: 'W' },
  AR: { fullName: 'Arkansas', region: 'S' },
  CA: { fullName: 'California', region: 'W' },
  CO: { fullName: 'Colorado', region: 'W' },
  CT: { fullName: 'Connecticut', region: 'NE' },
  DE: { fullName: 'Delaware', region: 'NE' },
  FL: { fullName: 'Florida', region: 'SE' },
  GA: { fullName: 'Georgia', region: 'SE' },
  HI: { fullName: 'Hawaii', region: 'W' },
  ID: { fullName: 'Idaho', region: 'NW' },
  IL: { fullName: 'Illinois', region: 'MW' },
  IN: { fullName: 'Indiana', region: 'MW' },
  IA: { fullName: 'Iowa', region: 'P' },
  KS: { fullName: 'Kansas', region: 'P' },
  KY: { fullName: 'Kentucky', region: 'MW' },
  LA: { fullName: 'Louisiana', region: 'S' },
  ME: { fullName: 'Maine', region: 'NE' },
  MD: { fullName: 'Maryland', region: 'NE' },
  MA: { fullName: 'Massachusetts', region: 'NE' },
  MI: { fullName: 'Michigan', region: 'N' },
  MN: { fullName: 'Minnesota', region: 'N' },
  MS: { fullName: 'Mississippi', region: 'SE' },
  MO: { fullName: 'Missouri', region: 'P' },
  MT: { fullName: 'Montana', region: 'NW' },
  NE: { fullName: 'Nebraska', region: 'P' },
  NV: { fullName: 'Nevada', region: 'W' },
  NH: { fullName: 'New Hampshire', region: 'NE' },
  NJ: { fullName: 'New Jersey', region: 'NE' },
  NM: { fullName: 'New Mexico', region: 'W' },
  NY: { fullName: 'New York', region: 'NE' },
  NC: { fullName: 'North Carolina', region: 'E' },
  ND: { fullName: 'North Dakota', region: 'P' },
  OH: { fullName: 'Ohio', region: 'MW' },
  OK: { fullName: 'Oklahoma', region: 'P' },
  OR: { fullName: 'Oregon', region: 'NW' },
  PA: { fullName: 'Pennsylvania', region: 'NE' },
  RI: { fullName: 'Rhode Island', region: 'NE' },
  SC: { fullName: 'South Carolina', region: 'SE' },
  SD: { fullName: 'South Dakota', region: 'P' },
  TN: { fullName: 'Tennessee', region: 'MW' },
  TX: { fullName: 'Texas', region: 'S' },
  UT: { fullName: 'Utah', region: 'W' },
  VT: { fullName: 'Vermont', region: 'NE' },
  VA: { fullName: 'Virginia', region: 'E' },
  WA: { fullName: 'Washington', region: 'NW' },
  WV: { fullName: 'West Virginia', region: 'E' },
  WI: { fullName: 'Wisconsin', region: 'N' },
  WY: { fullName: 'Wyoming', region: 'NW' },
};
